planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10

assembly_rtfg_manipulator:
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - PRMkConfigDefault
  projection_evaluator: joints(ur10_shoulder_pan,ur10_shoulder_lift)
  longest_valid_segment_fraction: 0.005
